const DEMO_PASSWORD = "Demo@1234";

const users = [
  { key: "admin", name: "Aarav Mehta", email: "admin@crm360.app", role: "admin", title: "Head of Revenue Operations", phone: "+91 98200 14521" },
  { key: "priya", name: "Priya Raman", email: "manager@crm360.app", role: "manager", title: "Sales Manager, Enterprise", phone: "+91 99870 33218" },
  { key: "daniel", name: "Daniel Okafor", email: "daniel.okafor@crm360.app", role: "manager", title: "Sales Manager, Mid-Market", phone: "+44 7700 900412" },
  { key: "rohan", name: "Rohan Kapoor", email: "executive@crm360.app", role: "executive", title: "Account Executive", phone: "+91 98111 20874" },
  { key: "sara", name: "Sara Lindqvist", email: "sara.lindqvist@crm360.app", role: "executive", title: "Account Executive", phone: "+46 70 123 45 67" },
  { key: "kabir", name: "Kabir Anand", email: "kabir.anand@crm360.app", role: "executive", title: "Business Development Rep", phone: "+91 97690 55102" },
  { key: "maya", name: "Maya Chen", email: "maya.chen@crm360.app", role: "executive", title: "Account Executive", phone: "+1 415 555 0142" },
];

const customers = [
  { name: "Ananya Deshpande", company: "Northwind Logistics", email: "ananya@northwindlogistics.in", phone: "+91 22 4012 7788", industry: "Logistics", status: "active", owner: "rohan", city: "Mumbai", state: "Maharashtra", country: "India", website: "northwindlogistics.in", ltv: 48500, notes: "Runs fleet operations for 14 warehouses. Renewal conversations typically start in Q4.", daysAgo: 160 },
  { name: "James Whitaker", company: "Brightline Health", email: "j.whitaker@brightlinehealth.com", phone: "+1 617 555 0198", industry: "Healthcare", status: "active", owner: "maya", city: "Boston", state: "MA", country: "United States", website: "brightlinehealth.com", ltv: 92000, notes: "Procurement requires HIPAA documentation before any expansion.", daysAgo: 150 },
  { name: "Ishita Bose", company: "Kestrel Fintech", email: "ishita.bose@kestrel.finance", phone: "+91 80 4567 1120", industry: "Finance", status: "active", owner: "sara", city: "Bengaluru", state: "Karnataka", country: "India", website: "kestrel.finance", ltv: 67500, notes: "Champion is the VP of Operations. Interested in API integrations.", daysAgo: 142 },
  { name: "Lukas Brenner", company: "Alpenrose Manufacturing", email: "l.brenner@alpenrose.de", phone: "+49 89 2019 4410", industry: "Manufacturing", status: "active", owner: "daniel", city: "Munich", state: "Bavaria", country: "Germany", website: "alpenrose.de", ltv: 118000, notes: "Multi-site rollout across three plants. Prefers quarterly business reviews.", daysAgo: 138 },
  { name: "Meera Pillai", company: "Coastline Retail Group", email: "meera@coastlineretail.co", phone: "+91 484 270 3321", industry: "Retail", status: "active", owner: "rohan", city: "Kochi", state: "Kerala", country: "India", website: "coastlineretail.co", ltv: 31200, notes: "42 stores. Seasonal spikes around Onam and Diwali.", daysAgo: 120 },
  { name: "Olivia Grant", company: "Harbor & Pine Hotels", email: "ogrant@harborpine.com", phone: "+1 206 555 0177", industry: "Hospitality", status: "active", owner: "maya", city: "Seattle", state: "WA", country: "United States", website: "harborpine.com", ltv: 54000, notes: "Wants a guest-experience dashboard for regional managers.", daysAgo: 112 },
  { name: "Vikram Joshi", company: "Sahyadri Energy", email: "vikram.joshi@sahyadrienergy.com", phone: "+91 20 6610 4455", industry: "Energy", status: "prospect", owner: "kabir", city: "Pune", state: "Maharashtra", country: "India", website: "sahyadrienergy.com", ltv: 0, notes: "Evaluating vendors for their solar installation business.", daysAgo: 96 },
  { name: "Emma Rousseau", company: "Lumière Media", email: "emma@lumieremedia.fr", phone: "+33 1 84 88 20 10", industry: "Media", status: "active", owner: "sara", city: "Paris", state: "Île-de-France", country: "France", website: "lumieremedia.fr", ltv: 27800, notes: "Small team, fast decisions. Likes monthly check-ins.", daysAgo: 90 },
  { name: "Arjun Malhotra", company: "Crestview Realty", email: "arjun@crestviewrealty.in", phone: "+91 11 4155 9020", industry: "Real Estate", status: "inactive", owner: "rohan", city: "New Delhi", state: "Delhi", country: "India", website: "crestviewrealty.in", ltv: 15400, notes: "Paused usage after restructuring. Revisit in two months.", daysAgo: 210 },
  { name: "Hannah Morales", company: "Summit Learning", email: "hmorales@summitlearning.org", phone: "+1 512 555 0133", industry: "Education", status: "active", owner: "maya", city: "Austin", state: "TX", country: "United States", website: "summitlearning.org", ltv: 22600, notes: "Non-profit pricing applied. Board approves budget in August.", daysAgo: 75 },
  { name: "Tanvi Reddy", company: "Quanta Cloudworks", email: "tanvi.reddy@quantacloud.io", phone: "+91 40 6723 8801", industry: "Technology", status: "active", owner: "kabir", city: "Hyderabad", state: "Telangana", country: "India", website: "quantacloud.io", ltv: 73400, notes: "Strong expansion potential into their support org.", daysAgo: 64 },
  { name: "George Whitfield", company: "Ferris & Clarke LLP", email: "gwhitfield@ferrisclarke.co.uk", phone: "+44 20 7946 0321", industry: "Finance", status: "churned", owner: "daniel", city: "London", state: "", country: "United Kingdom", website: "ferrisclarke.co.uk", ltv: 19800, notes: "Moved to an in-house tool. Left on good terms.", daysAgo: 240 },
  { name: "Nikhil Verma", company: "Orbit Freight", email: "nikhil@orbitfreight.in", phone: "+91 33 4060 1177", industry: "Logistics", status: "active", owner: "sara", city: "Kolkata", state: "West Bengal", country: "India", website: "orbitfreight.in", ltv: 38900, notes: "Uses the platform for dispatch coordination.", daysAgo: 52 },
  { name: "Sophie Tanaka", company: "Mori Design Studio", email: "sophie@moridesign.jp", phone: "+81 3 5555 0144", industry: "Media", status: "active", owner: "maya", city: "Tokyo", state: "", country: "Japan", website: "moridesign.jp", ltv: 12500, notes: "Design agency with 30 seats.", daysAgo: 41 },
  { name: "Rahul Nair", company: "Evergreen Clinics", email: "rahul.nair@evergreenclinics.in", phone: "+91 44 2811 6620", industry: "Healthcare", status: "prospect", owner: "rohan", city: "Chennai", state: "Tamil Nadu", country: "India", website: "evergreenclinics.in", ltv: 0, notes: "Pilot proposed for two clinics before chain-wide adoption.", daysAgo: 30 },
  { name: "Carlos Mendes", company: "Atlântico Foods", email: "carlos@atlanticofoods.pt", phone: "+351 21 555 0192", industry: "Retail", status: "active", owner: "daniel", city: "Lisbon", state: "", country: "Portugal", website: "atlanticofoods.pt", ltv: 44700, notes: "Distributor across Iberia. Needs Portuguese-language onboarding.", daysAgo: 24 },
  { name: "Aditi Kulkarni", company: "Pixelforge Games", email: "aditi@pixelforge.gg", phone: "+91 20 6700 2231", industry: "Technology", status: "active", owner: "kabir", city: "Pune", state: "Maharashtra", country: "India", website: "pixelforge.gg", ltv: 26300, notes: "Community team uses it to manage publisher relationships.", daysAgo: 16 },
  { name: "William Hart", company: "Granite Peak Construction", email: "whart@granitepeak.com", phone: "+1 303 555 0116", industry: "Real Estate", status: "active", owner: "priya", city: "Denver", state: "CO", country: "United States", website: "granitepeak.com", ltv: 81000, notes: "Enterprise account managed directly by Priya.", daysAgo: 9 },
];

const leads = [
  { name: "Kavya Iyer", company: "Saffron Hospitality", email: "kavya.iyer@saffronhotels.in", title: "Director of Operations", source: "referral", status: "new", value: 24000, owner: "rohan", followUp: 1, daysAgo: 2 },
  { name: "Ethan Caldwell", company: "Ridgeway Analytics", email: "ethan@ridgewayanalytics.com", title: "COO", source: "website", status: "new", value: 38000, owner: "maya", followUp: 2, daysAgo: 3 },
  { name: "Zara Qureshi", company: "Bloom Organics", email: "zara@bloomorganics.co", title: "Founder", source: "linkedin", status: "new", value: 9500, owner: "kabir", followUp: 3, daysAgo: 4 },
  { name: "Felix Wagner", company: "Nordlicht Robotics", email: "f.wagner@nordlicht.de", title: "Head of Sales", source: "event", status: "new", value: 56000, owner: "sara", followUp: 5, daysAgo: 5 },
  { name: "Riya Sethi", company: "UrbanNest Interiors", email: "riya@urbannest.in", title: "Managing Partner", source: "email_campaign", status: "new", value: 12800, owner: null, followUp: null, daysAgo: 1 },
  { name: "Marcus Bell", company: "Ironclad Security", email: "mbell@ironcladsec.com", title: "VP Customer Success", source: "cold_call", status: "contacted", value: 42000, owner: "maya", followUp: 0, daysAgo: 12 },
  { name: "Pooja Bhatt", company: "Greenleaf Agritech", email: "pooja.bhatt@greenleafagri.in", title: "CEO", source: "partner", status: "contacted", value: 31000, owner: "rohan", followUp: 2, daysAgo: 14 },
  { name: "Liam O'Connor", company: "Shamrock Travel", email: "liam@shamrocktravel.ie", title: "General Manager", source: "website", status: "contacted", value: 15500, owner: "daniel", followUp: 4, daysAgo: 10 },
  { name: "Neha Agarwal", company: "Finstack Payments", email: "neha@finstack.in", title: "Head of Partnerships", source: "linkedin", status: "contacted", value: 64000, owner: "sara", followUp: -1, daysAgo: 18 },
  { name: "Samuel Adeyemi", company: "Lagos Mobility", email: "samuel@lagosmobility.ng", title: "CTO", source: "event", status: "contacted", value: 27000, owner: "kabir", followUp: 6, daysAgo: 9 },
  { name: "Chloe Martin", company: "Maison Verre", email: "chloe@maisonverre.fr", title: "Operations Lead", source: "referral", status: "qualified", value: 48000, owner: "sara", followUp: 1, daysAgo: 22 },
  { name: "Aditya Rao", company: "Helix Biosciences", email: "aditya.rao@helixbio.in", title: "Director, Commercial", source: "website", status: "qualified", value: 88000, owner: "rohan", followUp: 3, daysAgo: 26 },
  { name: "Grace Kim", company: "Tidewater Insurance", email: "grace.kim@tidewaterins.com", title: "VP Distribution", source: "partner", status: "qualified", value: 105000, owner: "priya", followUp: 2, daysAgo: 30 },
  { name: "Omar Haddad", company: "Cedar Logistics", email: "omar@cedarlogistics.ae", title: "Regional Director", source: "cold_call", status: "qualified", value: 36000, owner: "maya", followUp: 7, daysAgo: 20 },
  { name: "Divya Menon", company: "Lotus Wellness", email: "divya@lotuswellness.in", title: "Founder & CEO", source: "email_campaign", status: "proposal", value: 22000, owner: "kabir", followUp: 1, daysAgo: 34 },
  { name: "Benjamin Scott", company: "Clearwater Utilities", email: "bscott@clearwaterutil.com", title: "Procurement Manager", source: "event", status: "proposal", value: 132000, owner: "daniel", followUp: 2, daysAgo: 40 },
  { name: "Anika Hoffmann", company: "Bergmann Automotive", email: "a.hoffmann@bergmann-auto.de", title: "Head of Digital", source: "linkedin", status: "proposal", value: 76000, owner: "sara", followUp: 0, daysAgo: 38 },
  { name: "Siddharth Jain", company: "Vertex Infra", email: "siddharth@vertexinfra.in", title: "Chief Revenue Officer", source: "referral", status: "proposal", value: 59000, owner: "rohan", followUp: 4, daysAgo: 29 },
  { name: "Laura Bennett", company: "Oakridge Schools", email: "lbennett@oakridgeschools.org", title: "Director of Technology", source: "website", status: "won", value: 18500, owner: "maya", closedDaysAgo: 6, daysAgo: 70 },
  { name: "Harsh Vardhan", company: "Monsoon Beverages", email: "harsh@monsoonbev.in", title: "Head of Sales", source: "partner", status: "won", value: 41000, owner: "rohan", closedDaysAgo: 12, daysAgo: 64 },
  { name: "Isabella Rossi", company: "Trattoria Group", email: "isabella@trattoriagroup.it", title: "Owner", source: "referral", status: "won", value: 16000, owner: "sara", closedDaysAgo: 38, daysAgo: 90 },
  { name: "Noah Fischer", company: "Alpine Outfitters", email: "noah@alpineoutfitters.ch", title: "COO", source: "event", status: "won", value: 52000, owner: "daniel", closedDaysAgo: 45, daysAgo: 100 },
  { name: "Sneha Patil", company: "Rangoli Crafts", email: "sneha@rangolicrafts.in", title: "Founder", source: "linkedin", status: "won", value: 8700, owner: "kabir", closedDaysAgo: 70, daysAgo: 115 },
  { name: "Ryan Mitchell", company: "Keystone Dental", email: "ryan@keystonedental.com", title: "Practice Director", source: "website", status: "won", value: 29500, owner: "maya", closedDaysAgo: 82, daysAgo: 130 },
  { name: "Yusuf Khan", company: "Crescent Pharma", email: "yusuf.khan@crescentpharma.in", title: "VP Sales", source: "cold_call", status: "won", value: 97000, owner: "priya", closedDaysAgo: 105, daysAgo: 160 },
  { name: "Elena Petrova", company: "Baltic Shipping", email: "elena@balticshipping.lv", title: "Commercial Director", source: "partner", status: "won", value: 63000, owner: "daniel", closedDaysAgo: 128, daysAgo: 175 },
  { name: "Aman Gupta", company: "Brewhouse Collective", email: "aman@brewhouse.in", title: "Co-founder", source: "referral", status: "won", value: 14200, owner: "rohan", closedDaysAgo: 150, daysAgo: 190 },
  { name: "Charlotte Evans", company: "Evans & Co. Architects", email: "cevans@evansarchitects.co.uk", title: "Partner", source: "website", status: "lost", value: 21000, owner: "sara", closedDaysAgo: 20, daysAgo: 60, lostReason: "Chose a lower-cost competitor" },
  { name: "Manish Tiwari", company: "Skyline Telecom", email: "manish@skylinetelecom.in", title: "Director IT", source: "event", status: "lost", value: 74000, owner: "kabir", closedDaysAgo: 55, daysAgo: 110, lostReason: "Budget frozen for the fiscal year" },
  { name: "Jack Robinson", company: "Pinnacle Fitness", email: "jack@pinnaclefitness.com", title: "Owner", source: "cold_call", status: "lost", value: 11000, owner: "maya", closedDaysAgo: 96, daysAgo: 140, lostReason: "No response after proposal" },
];

const leadNotes = {
  "Aditya Rao": ["Discovery call went well. They need territory-based lead routing for 40 reps.", "Security review questionnaire sent to their IT team."],
  "Grace Kim": ["Executive sponsor confirmed. Wants a phased rollout starting with the Northeast region."],
  "Benjamin Scott": ["Proposal v2 shared with revised onboarding timeline.", "Legal is reviewing the MSA redlines."],
  "Anika Hoffmann": ["Needs German data residency confirmation before signing."],
  "Marcus Bell": ["Left voicemail, followed up via email with case study."],
  "Kavya Iyer": ["Referred by Ananya at Northwind. Warm intro scheduled."],
  "Chloe Martin": ["Budget approved for 25 seats. Decision expected within two weeks."],
  "Neha Agarwal": ["Asked for pricing on the annual plan with SSO."],
};

const tasks = [
  { title: "Send revised proposal to Clearwater Utilities", description: "Include the updated onboarding timeline and volume discount.", owner: "daniel", creator: "priya", priority: "high", status: "in_progress", due: 1, lead: "Benjamin Scott" },
  { title: "Security questionnaire follow-up with Helix", description: "Chase IT for the completed questionnaire and schedule a call with our security lead.", owner: "rohan", creator: "priya", priority: "high", status: "todo", due: 0, lead: "Aditya Rao" },
  { title: "Quarterly business review — Alpenrose", description: "Prepare usage report and expansion proposal for the Munich plant.", owner: "daniel", creator: "daniel", priority: "medium", status: "todo", due: 5, customer: "Lukas Brenner" },
  { title: "Onboarding kickoff for Oakridge Schools", description: "Walk the IT team through account setup and data import.", owner: "maya", creator: "maya", priority: "medium", status: "in_progress", due: 2, customer: null, lead: "Laura Bennett" },
  { title: "Call Marcus Bell at Ironclad Security", description: "Second attempt. Reference the Brightline Health case study.", owner: "maya", creator: "maya", priority: "high", status: "todo", due: 0, lead: "Marcus Bell" },
  { title: "Prepare pricing for Finstack SSO plan", description: "Annual plan with SSO add-on, 60 seats.", owner: "sara", creator: "daniel", priority: "high", status: "todo", due: -1, lead: "Neha Agarwal" },
  { title: "Renewal check-in with Northwind Logistics", description: "Discuss renewal terms and warehouse expansion.", owner: "rohan", creator: "rohan", priority: "medium", status: "todo", due: 6, customer: "Ananya Deshpande" },
  { title: "Share HIPAA documentation with Brightline", description: "Send the latest compliance pack to procurement.", owner: "maya", creator: "priya", priority: "high", status: "completed", due: -3, customer: "James Whitaker" },
  { title: "Draft pilot plan for Evergreen Clinics", description: "Two-clinic pilot with success criteria and a 30-day timeline.", owner: "rohan", creator: "priya", priority: "medium", status: "in_progress", due: 3, customer: "Rahul Nair" },
  { title: "Book discovery call with Nordlicht Robotics", description: "Met Felix at SaaS Summit Berlin.", owner: "sara", creator: "sara", priority: "medium", status: "todo", due: 4, lead: "Felix Wagner" },
  { title: "Update case study with Kestrel Fintech results", description: "Get approval from Ishita for the 32% response-time improvement stat.", owner: "sara", creator: "sara", priority: "low", status: "todo", due: 9, customer: "Ishita Bose" },
  { title: "Confirm data residency for Bergmann Automotive", description: "Coordinate with infrastructure team on EU hosting details.", owner: "sara", creator: "daniel", priority: "high", status: "in_progress", due: 1, lead: "Anika Hoffmann" },
  { title: "Send welcome pack to Granite Peak", description: "Executive welcome letter and onboarding schedule.", owner: "priya", creator: "admin", priority: "low", status: "completed", due: -6, customer: "William Hart" },
  { title: "Qualify inbound lead from UrbanNest Interiors", description: "Unassigned inbound lead from the Diwali email campaign.", owner: "kabir", creator: "priya", priority: "medium", status: "todo", due: 2, lead: "Riya Sethi" },
  { title: "Proposal walkthrough with Lotus Wellness", description: "Walk Divya through the proposal and answer pricing questions.", owner: "kabir", creator: "kabir", priority: "high", status: "todo", due: 1, lead: "Divya Menon" },
  { title: "Review Q3 pipeline with the enterprise team", description: "Pipeline hygiene: close-date accuracy and stale opportunities.", owner: "priya", creator: "admin", priority: "medium", status: "todo", due: 3 },
  { title: "Win-back outreach to Crestview Realty", description: "Share new reporting features released since they paused.", owner: "rohan", creator: "rohan", priority: "low", status: "todo", due: 12, customer: "Arjun Malhotra" },
  { title: "Portuguese onboarding materials for Atlântico", description: "Coordinate translation of the admin guide.", owner: "daniel", creator: "daniel", priority: "medium", status: "completed", due: -2, customer: "Carlos Mendes" },
  { title: "Monthly check-in with Lumière Media", description: "", owner: "sara", creator: "sara", priority: "low", status: "completed", due: -8, customer: "Emma Rousseau" },
  { title: "Audit user permissions for new hires", description: "Make sure new executives have the right role assignments.", owner: "admin", creator: "admin", priority: "medium", status: "in_progress", due: 2 },
  { title: "Follow up with Saffron Hospitality", description: "Warm intro from Northwind — schedule a first call.", owner: "rohan", creator: "rohan", priority: "medium", status: "todo", due: 1, lead: "Kavya Iyer" },
  { title: "Send contract to Maison Verre", description: "Contract for 25 seats, annual billing.", owner: "sara", creator: "sara", priority: "high", status: "todo", due: 2, lead: "Chloe Martin" },
  { title: "Expansion proposal for Quanta Cloudworks support team", description: "Estimate seats for the 80-person support org.", owner: "kabir", creator: "priya", priority: "medium", status: "todo", due: 8, customer: "Tanvi Reddy" },
  { title: "Collect NPS feedback from Harbor & Pine", description: "", owner: "maya", creator: "maya", priority: "low", status: "completed", due: -10, customer: "Olivia Grant" },
];

const interactions = [
  { customer: "Ananya Deshpande", type: "meeting", summary: "Quarterly review with fleet operations team", body: "Reviewed dispatch SLAs. They want better reporting on late deliveries.", daysAgo: 8, actor: "rohan" },
  { customer: "Ananya Deshpande", type: "email", summary: "Shared renewal pricing options", body: "Sent three renewal options with multi-year discounts.", daysAgo: 3, actor: "rohan" },
  { customer: "Ananya Deshpande", type: "call", summary: "Intro call for Saffron Hospitality referral", body: "Ananya agreed to introduce us to Kavya at Saffron.", daysAgo: 2, actor: "rohan" },
  { customer: "James Whitaker", type: "call", summary: "Procurement sync on compliance", body: "Procurement confirmed they need the HIPAA pack before expanding to 3 more clinics.", daysAgo: 5, actor: "maya" },
  { customer: "James Whitaker", type: "email", summary: "Sent HIPAA documentation", daysAgo: 3, actor: "maya" },
  { customer: "Ishita Bose", type: "meeting", summary: "API integration workshop", body: "Walked their engineers through webhooks and the REST API.", daysAgo: 11, actor: "sara" },
  { customer: "Lukas Brenner", type: "meeting", summary: "On-site visit at Munich plant", body: "Toured the plant and met the shift supervisors who use the platform daily.", daysAgo: 15, actor: "daniel" },
  { customer: "Lukas Brenner", type: "note", summary: "Expansion likely in Q1", body: "Plant 3 manager is enthusiastic. Budget decision in January.", daysAgo: 14, actor: "daniel" },
  { customer: "Meera Pillai", type: "call", summary: "Festive season readiness call", daysAgo: 20, actor: "rohan" },
  { customer: "Olivia Grant", type: "email", summary: "Sent dashboard mockups", body: "Shared early mockups of the regional manager dashboard.", daysAgo: 6, actor: "maya" },
  { customer: "Tanvi Reddy", type: "meeting", summary: "Support org discovery session", body: "Their support team has 80 agents and uses spreadsheets for escalations.", daysAgo: 4, actor: "kabir" },
  { customer: "Rahul Nair", type: "call", summary: "Pilot scoping call", body: "Agreed on two clinics in Chennai for the pilot.", daysAgo: 7, actor: "rohan" },
  { customer: "Carlos Mendes", type: "email", summary: "Onboarding schedule confirmed", daysAgo: 9, actor: "daniel" },
  { customer: "William Hart", type: "meeting", summary: "Executive kickoff", body: "Kickoff with the CFO and head of project management.", daysAgo: 7, actor: "priya" },
  { customer: "Aditi Kulkarni", type: "note", summary: "Community team loves the pipeline board", daysAgo: 5, actor: "kabir" },
  { customer: "Emma Rousseau", type: "call", summary: "Monthly check-in", body: "No blockers. Considering adding 5 seats next quarter.", daysAgo: 8, actor: "sara" },
  { customer: "George Whitfield", type: "email", summary: "Offboarding confirmation", body: "Exported their data and confirmed account closure.", daysAgo: 45, actor: "daniel" },
];

module.exports = { DEMO_PASSWORD, users, customers, leads, leadNotes, tasks, interactions };
